routes/admin.php
<?php

Auth::routes();

Route::get('{page}', 'FrontEndController@page');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:Administrador']], function () {
    Route::resource('users', 'UsersController');
    Route::resource('pages', 'PagesController');
    Route::resource('trucks', 'TrucksController');
    Route::resource('components', 'ComponentsController');
    Route::get('components/{type}/{id}/create', 'ComponentsController@create')->name('components.create');

    /* Parts */
    Route::get('parts/images', 'PartsController@filemanager')->name('parts.filemanager');
    Route::get('imagenes/conex', 'PartsController@getConnection')->name('imagenes.conex');
    Route::post('imagenes/conex', 'PartsController@postConnection')->name('imagenes.conex');

    Route::resource('resources', 'ResourcesController', [
      'only' => ['store', 'destroy']
  ]);
});

routes/web.php
<?php

Route::get('/', 'FrontEndController@home');

Route::redirect('/admin', '/admin/users');

Route::get('/camiones/{truck}', 'FrontEndController@truck')->name('truck');
Route::get('/repuestos/resultados', 'FrontEndController@search')->name('search');
Route::get('/repuestos/promocion', 'FrontEndController@onsale')->name('onsale');
Route::get('/repuestos/{part}', 'FrontEndController@part')->name('part');
Route::get('/carrito', 'CartController@cart')->name('cart');
Route::post('/parttocart', 'CartController@addPartToCart')->name('addPartToCart');
Route::post('/cart/update', 'CartController@update')->name('cart.update');
Route::get('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart/order', 'CartController@order')->name('cart.order')->middleware('auth');

Route::get('/success', 'CartController@success')->name('cart.success')->middleware('auth');

/* Routes related with admin */
include('admin.php');

app/Component.php
<?php

namespace App;

use App\Resource;
use App\Traits\ModelTrait;
use Illuminate\Database\Eloquent\Model;

class Component extends Model
{
    use ModelTrait;
    protected $fillable = ['key', 'title', 'subtitle', 'content', 'attributes','status', 'componentable_id', 'componentable_type'];
    protected $with = ['resources'];
    protected $appends = ['model_name', 'plural_name'];

    public function resources()
    {
        return $this->morphMany(Resource::class, 'imageable');
    }

    public function componentable()
    {
        return $this->morphTo();
    }

    public function getTypeOfAttribute()
    {
        return str_plural(strtolower(class_basename($this->componentable)));
    }
}

app/Http/Controllers/Admin/ComponentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Resource;
use App\Component;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ComponentsController extends Controller
{
    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create($type, $id)
    {
        $name = "App\\{$type}";
        $source = $name::find($id);
        return view('admin.component.create', \compact('source'));
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'key' => 'required'
        ]);
        $data = $request->all();
        $component = new Component($data);
        $component->save();
        if($request->hasFile('resource')) {
            $file = $request->file('resource');
            $component->resources()->save(new Resource([ 
                'url' => $file->store('resources'),
                'mime' => \Illuminate\Support\Facades\File::mimeType($file),
                'size' => \Illuminate\Support\Facades\File::size($file)
            ]));
        }
        return redirect()->route("{$component->componentable->plural_name}.edit", $component->componentable);
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit(Component $component)
    {
        return view('admin.component.edit', \compact('component'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Component $component)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);
        $data = $request->all();
        $data['status'] = $request->has('status') ? 1 : 0;
        $component->update($data);
        return redirect()->route("{$component->componentable->plural_name}.edit", $component->componentable);
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy(Component $component)
    {
        $component->delete();
        return redirect()->route("{$component->componentable->plural_name}.edit", $component->componentable);
    }
}

resources/views/admin/component/create.blade.php
@extends('admin.layouts.app')

@section('breadcrumb')
    {!! Breadcrumbs::render('create-component', $source, Request::get('name')) !!}
@endsection

@section('title', 'Crear Componente')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <strong>Crear</strong> {{ Request::get('name') }}
                </div>
                <form method="POST" action="{{ route('components.store') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="card-block">
                        <input type="text" name="componentable_id" hidden value="{{ $source->id }}">
                        <input type="text" name="componentable_type" hidden value="{{ 'App\\' . $source->model_name }}">
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">Título</label>
                                <input type="text" class="form-control @if($errors->has('title')) is-invalid @endif" id="title" name="title" placeholder="Título">
                                @if($errors->has('title'))
                                    <div class="invalid-feedback">{{ $errors->first('title') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="subtitle">Subtitulo</label>
                                <input type="text" class="form-control @if($errors->has('subtitle')) is-invalid @endif" id="subtitle" name="subtitle" placeholder="Subtitulo">
                                @if($errors->has('subtitle'))
                                    <div class="invalid-feedback">{{ $errors->first('subtitle') }}</div>
                                @endif
                            </div>
                        </div>
                        <input type="text" name="key" hidden value="{{ Request::get('key') }}">
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="description">Descripción</label>
                                <textarea class="description form-control @if($errors->has('description')) is-invalid @endif" rows="3" name="content" placeholder="Descripción"></textarea>
                                @if($errors->has('description'))
                                    <div class="invalid-feedback">{{ $errors->first('description') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="logo">Imagen</label>
                                <input-file-preview name="resource" accepted="image/*">
                                </input-file-preview>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a href="{{ route("{$source->plural_name}.edit", $source) }}" class="btn btn-default">Volver</a>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/component/edit.blade.php
@extends('admin.layouts.app')

@section('breadcrumb')
    {!! Breadcrumbs::render('component', $component->componentable, $component) !!}
@endsection

@section('title', 'Editar Componente')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <strong>Editar</strong> Componente
                </div>
                <form method="POST" action="{{ route('components.update', $component) }}">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="card-block">
                        <div class="row">
                            <div class="form-group col-sm-12 @if($errors->has('title')) has-danger @endif">
                                <label for="title">Título</label>
                                <input type="text" class="form-control" id="title" name="title" placeholder="Título" value="{{ $component->title }}">
                                @if($errors->has('title'))
                                    <div class="form-control-feedback">{{ $errors->first('title') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12 @if($errors->has('subtitle')) has-danger @endif">
                                <label for="subtitle">Subtitulo</label>
                                <input type="text" class="form-control" id="subtitle" name="subtitle" placeholder="Subtitulo" value="{{ $component->subtitle }}">
                                @if($errors->has('subtitle'))
                                    <div class="form-control-feedback">{{ $errors->first('subtitle') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="subtitle">Estado</label>
                                <div>
                                    <label class="switch switch-text switch-pill switch-primary">
                                        <input type="checkbox" name="status" class="switch-input" @if($component->status) checked @endif>
                                        <span class="switch-label" data-on="On" data-off="Off"></span>
                                        <span class="switch-handle"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12 @if($errors->has('description')) has-danger @endif">
                                <label for="description">Descripción</label>
                                <textarea class="description form-control" rows="3" name="content" placeholder="Descripción">{!! $component->content !!}</textarea>
                                @if($errors->has('description'))
                                    <div class="form-control-feedback">{{ $errors->first('description') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 form-group">
                                <label for="description">Recursos</label>
                                <drag-n-drop :images="{{ $component->resources }}" name="{{ $component->model_name }}" id="{{ $component->id }}" url="{{ route('resources.store', $component) }}"></drag-n-drop>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a href="{{ route("{$component->type_of}.edit", $component->componentable) }}" class="btn btn-default">Volver</a>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection