routes/admin.php
<?php

Auth::routes();

Route::get('{page}', 'FrontEndController@page');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:Administrador']], function () {
    Route::resource('users', 'UsersController');
    Route::resource('pages', 'PagesController');
    Route::resource('trucks', 'TrucksController');
    Route::resource('components', 'ComponentsController');
    Route::get('components/{type}/{id}/create', 'ComponentsController@create')->name('components.create');

    /* Parts */
    Route::get('parts/images', 'PartsController@filemanager')->name('parts.filemanager');
    Route::get('imagenes/conex', 'PartsController@getConnection')->name('imagenes.conex');
    Route::post('imagenes/conex', 'PartsController@postConnection')->name('imagenes.conex');

    Route::resource('resources', 'ResourcesController', [
      'only' => ['store', 'destroy']
  ]);
});

routes/web.php
<?php

Route::get('/', 'FrontEndController@home');

Route::redirect('/admin', '/admin/users');

Route::get('/camiones/{truck}', 'FrontEndController@truck')->name('truck');
Route::get('/repuestos/resultados', 'FrontEndController@search')->name('search');
Route::get('/repuestos/promocion', 'FrontEndController@onsale')->name('onsale');
Route::get('/repuestos/{part}', 'FrontEndController@part')->name('part');
Route::get('/carrito', 'CartController@cart')->name('cart');
Route::post('/parttocart', 'CartController@addPartToCart')->name('addPartToCart');
Route::post('/cart/update', 'CartController@update')->name('cart.update');
Route::get('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart/order', 'CartController@order')->name('cart.order')->middleware('auth');

Route::get('/success', 'CartController@success')->name('cart.success')->middleware('auth');

/* Routes related with admin */
include('admin.php');

resources/views/admin/page/content.blade.php
<div class="col-md-12">
    <div class="row justify-content-sm-between">
        <h3 class="m-0 font-weight-normal">Contenido</h3>
        @if(count($page->creatableComponents))
            <div class="btn-group">
                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                    Agregar
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    @foreach($page->creatableComponents as $creatable)
                        <a class="dropdown-item" href="{{ route('components.create', ['type' => $page->model_name, 'id' => $page->id, 'key' => $creatable->key, 'name' => $creatable->name]) }}">{{ $creatable->name }}</a>
                    @endforeach
                </div>
            </div>
        @endif
    </div>
    <br>
    <div class="row">
        <table class="table col btn-shadow">
            <thead>
                <tr>
                    <th>Título</th>
                    <th></th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach($page->components as $component)
                    <tr>
                        <td>{{ $component->title }}</td>
                        <td>
                            @if(in_array($component->key, $page->creatableComponents->pluck('key')->toArray()))
                                <span class="badge badge-warning">{{ $page->creatableComponents->where('key', $component->key)->first()->name }}</span>
                            @endif
                        </td>
                        <td>
                            @if($component->status)
                                <span class="badge badge-success">Activo</span>
                            @else
                                <span class="badge badge-danger">Inactivo</span>
                            @endif
                        </td>
                        <td>
                            <a href="{{ route('components.edit', $component) }}" class="btn btn-primary btn-sm">Editar</a>
                            <delete route="{{ route('components.destroy', $component) }}" token="{{ csrf_token() }}"></delete>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="m-3"></div>
</div>

resources/views/admin/page/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Crear Página')

@section('breadcrumb')
    {!! Breadcrumbs::render('create-page') !!}
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card btn-shadow">
                <div class="card-header">
                    <strong>Crear</strong> Página
                </div>
                <form method="POST" action="{{ route('pages.store') }}">
                    {{ csrf_field() }}
                    <div class="card-block">
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">Título</label>
                                <input type="text" class="form-control @if($errors->has('title')) is-invalid @endif" id="title" name="title" placeholder="Título">
                                <small class="form-text text-muted">Máximo 70 carácteres.</small>
                                @if($errors->has('title'))
                                    <div class="invalid-feedback">{{ $errors->first('title') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="description">Descripción</label>
                                <textarea class="form-control @if($errors->has('description')) is-invalid @endif" rows="3" name="description" placeholder="Descripción"></textarea>
                                <small class="form-text text-muted">Máximo 156 carácteres.</small>
                                @if($errors->has('description'))
                                    <div class="invalid-feedback">{{ $errors->first('description') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12 col-md-3">
                                <label for="description">Vista</label>
                                <select class="custom-select form-control @if($errors->has('view')) is-invalid @endif" name="view">
                                    <option selected disabled>Seleccionar Vista</option>
                                    @foreach($views as $view)
                                        <option value="{{ $view }}">{{ $view }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('view'))
                                    <div class="invalid-feedback">{{ $errors->first('view') }}</div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a href="{{ route('pages.index') }}" class="btn btn-default">Volver</a>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/page/edit.blade.php
@extends('admin.layouts.app')

@section('title', $page->title)

@section('breadcrumb')
    {!! Breadcrumbs::render('page', $page) !!}
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card btn-shadow">
                <div class="card-header">
                    <strong>Editar</strong> Página
                </div>
                <form method="POST" action="{{ route('pages.update', $page) }}">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="card-block">
                        <div class="row">
                            <div class="form-group col-sm-12 @if($errors->has('title')) has-danger @endif">
                                <label for="title">Título</label>
                                <input type="text" class="form-control" id="title" name="title" placeholder="Título" value="{{ $page->title }}" v-model="seo.name">
                                <small class="form-text text-muted">Máximo 70 carácteres.</small>
                                @if($errors->has('title'))
                                    <div class="form-control-feedback">{{ $errors->first('title') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12 @if($errors->has('subtitle')) has-danger @endif">
                                <label for="subtitle">Url</label>
                                <input type="text" class="form-control" id="subtitle" name="subtitle" placeholder="Título" value="{{ $page->slug }}" disabled>
                                @if($errors->has('subtitle'))
                                    <div class="form-control-feedback">{{ $errors->first('subtitle') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12 @if($errors->has('description')) has-danger @endif">
                                <label for="description">Descripción</label>
                                <textarea class="form-control" rows="3" name="description" placeholder="Descripción" v-model="seo.description">{!! $page->description !!}</textarea>
                                <small class="form-text text-muted">Máximo 156 carácteres.</small>
                                @if($errors->has('description'))
                                    <div class="form-control-feedback">{{ $errors->first('description') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12 @if($errors->has('description')) has-danger @endif">
                                <label for="description">Vista previa</label>
                                <div class="seo-preview">
                                    <img src="https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg">
                                    <div>
                                        <h3>{{ config('app.name') }} - @{{ seo.name }}</h3>
                                        <span>{{ url('/') . '/' . $page->slug }}</span>
                                        <p>@{{ seoDescription(seo.description) }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a href="{{ route('pages.index') }}" class="btn btn-default">Volver</a>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Page Components -->
    @include('admin.page.content')
@endsection

@push('script')
    <script>
        var seo = {
            name: '{{ $page->title }}',
            description: '{{ $page->description }}'
        }   
    </script>
@endpush

resources/views/admin/page/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Páginas')

@section('breadcrumb')
    {!! Breadcrumbs::render('pages') !!}
@endsection

@section('content')
    <div class="row justify-content-sm-between">
        <h3 class="m-0 font-weight-normal">Páginas</h3>
        <a href="{{ route('pages.create') }}" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Nueva Página</a>
    </div>
    <br>
    <div class="row">
        <table class="table col btn-shadow">
            <thead>
                <tr>
                <th>#</th>
                <th>Título</th>
                <th>Url</th>
                <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach($pages as $page)
                    <tr>
                        <th scope="row">{{ $page->id }}</th>
                        <td>{{ $page->title }}</td>
                        <td>{{ $page->slug }}</td>
                        <td>
                            <a href="{{ route('pages.edit', $page) }}" class="btn btn-primary btn-sm">Editar</a>
                            {{--  <button type="button" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Borrar</button>  --}}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="row">
        {{ $pages->links() }}
    </div>
@endsection