routes/admin.php
<?php

Auth::routes();

Route::get('{page}', 'FrontEndController@page');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:Administrador']], function () {
    Route::resource('users', 'UsersController');
    Route::resource('pages', 'PagesController');
    Route::resource('trucks', 'TrucksController');
    Route::resource('components', 'ComponentsController');
    Route::get('components/{type}/{id}/create', 'ComponentsController@create')->name('components.create');

    /* Parts */
    Route::get('parts/images', 'PartsController@filemanager')->name('parts.filemanager');
    Route::get('imagenes/conex', 'PartsController@getConnection')->name('imagenes.conex');
    Route::post('imagenes/conex', 'PartsController@postConnection')->name('imagenes.conex');

    Route::resource('resources', 'ResourcesController', [
      'only' => ['store', 'destroy']
  ]);
});

routes/web.php
<?php

Route::get('/', 'FrontEndController@home');

Route::redirect('/admin', '/admin/users');

Route::get('/camiones/{truck}', 'FrontEndController@truck')->name('truck');
Route::get('/repuestos/resultados', 'FrontEndController@search')->name('search');
Route::get('/repuestos/promocion', 'FrontEndController@onsale')->name('onsale');
Route::get('/repuestos/{part}', 'FrontEndController@part')->name('part');
Route::get('/carrito', 'CartController@cart')->name('cart');
Route::post('/parttocart', 'CartController@addPartToCart')->name('addPartToCart');
Route::post('/cart/update', 'CartController@update')->name('cart.update');
Route::get('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart/order', 'CartController@order')->name('cart.order')->middleware('auth');

Route::get('/success', 'CartController@success')->name('cart.success')->middleware('auth');

/* Routes related with admin */
include('admin.php');

app/Truck.php
<?php

namespace App;

use App\TruckFamily;
use App\Traits\ModelTrait;
use Illuminate\Database\Eloquent\Model;

class Truck extends Model
{
    use ModelTrait;
    protected $fillable = ['name', 'description', 'load_amount', 'price', 'specs', 'specs_image', 'dimensions', 'dimensions_image', 'accessories', 'accessories_image', 'featured_image', 'catalog', 'status'];

    public function family()
    {
        return $this->belongsTo(TruckFamily::class, 'truck_family_id');
    }

    public function resources()
    {
        return $this->morphMany(Resource::class, 'imageable');
    }

    public function getSpecsImageAttribute($value)
    {
        if($value) {
            return asset("storage/{$value}");
        }
    }

    public function getDimensionsImageAttribute($value)
    {
        if($value) {
            return asset("storage/{$value}");
        }
    }

    public function getFeaturedImageAttribute($value)
    {
        if($value) {
            return asset("storage/{$value}");
        }
    }

    public function getAccessoriesImageAttribute($value)
    {
        if($value) {
            return asset("storage/{$value}");
        }
    }

    public function getCatalogAttribute($value)
    {
        if($value) {
            return asset("storage/{$value}");
        }
    }
}

app/Http/Controllers/Admin/TrucksController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Truck;
use App\TruckFamily;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TrucksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $trucks = Truck::with('family')->orderBy('truck_family_id')->paginate(25);
        return view('admin.truck.index', \compact('trucks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $families = TruckFamily::all();
        return view('admin.truck.create', \compact('families'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
            'load_amount' => 'required',
            'price' => 'required',
            'featured_image' => 'required|mimes:jpeg,bmp,png',
            'truck_family_id' => 'required',
            'catalog' => 'sometimes|nullable|mimes:pdf',
            'specs_image' => 'sometimes|nullable|mimes:jpeg,bmp,png',
            'dimensions_image' => 'sometimes|nullable|mimes:jpeg,bmp,png',
            'accessories_image' => 'sometimes|nullable|mimes:jpeg,bmp,png',            
        ]);
        $data = $request->except(['truck_family_id', 'specs_image', 'featured_image', 'dimensions_image', 'accessories_image', 'catalog']);
        /* Store Catalog pdf */
        if($request->hasFile('catalog')) {
            $data['catalog'] = $request->file('catalog')->store('resources');
        }
        /* Store Featured image */
        if($request->hasFile('featured_image')) {
            $data['featured_image'] = $request->file('featured_image')->store('resources');
        }
        /* Store Tech specs image */
        if($request->hasFile('specs_image')) {
            $data['specs_image'] = $request->file('specs_image')->store('resources');
        }
        /* Store Dimensaions image */
        if($request->hasFile('dimensions_image')) {
            $data['dimensions_image'] = $request->file('dimensions_image')->store('resources');
        }
        /* Store Accessories image */
        if($request->hasFile('accessories_image')) {
            $data['accessories_image'] = $request->file('accessories_image')->store('resources');
        }
        $family = TruckFamily::where('id', $request->input('truck_family_id'))->first();
        $family->trucks()->save(new Truck($data));
        return redirect()->route('trucks.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Truck $truck)
    {
        $families = TruckFamily::all();
        return view('admin.truck.edit', \compact('truck', 'families'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Truck $truck)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
            'load_amount' => 'required',
            'price' => 'required',
            'featured_image' => 'sometimes|nullable|mimes:jpeg,bmp,png',
            'truck_family_id' => 'required',
            'catalog' => 'sometimes|nullable|mimes:pdf'
        ]);
        $family = TruckFamily::where('id', $request->input('truck_family_id'))->first();
        $data = $request->except(['truck_family_id', 'specs_image', 'featured_image', 'dimensions_image', 'accessories_image', 'catalog']);
        $data['status'] = $request->has('status') ? 1 : 0;
        /* Store Catalog pdf */
        if($request->hasFile('catalog')) {
            $data['catalog'] = $request->file('catalog')->store('resources');
        }
        /* Store Featured image */
        if($request->hasFile('featured_image')) {
            $data['featured_image'] = $request->file('featured_image')->store('resources');
        }
        /* Store Tech specs image */
        if($request->hasFile('specs_image')) {
            $data['specs_image'] = $request->file('specs_image')->store('resources');
        }
        /* Store Dimensaions image */
        if($request->hasFile('dimensions_image')) {
            $data['dimensions_image'] = $request->file('dimensions_image')->store('resources');
        }
        /* Store Accessories image */
        if($request->hasFile('accessories_image')) {
            $data['accessories_image'] = $request->file('accessories_image')->store('resources');
        }
        $truck->update($data);
        $truck->family()->associate($family);
        $truck->save();
        return redirect()->route('trucks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Truck $truck)
    {
        $truck->delete();
        return redirect()->route('trucks.index');
    }
}

resources/views/admin/truck/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Crear Camión')

@section('breadcrumb')
    {!! Breadcrumbs::render('create-truck') !!}
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card btn-shadow">
                <div class="card-header">
                    <strong>Crear</strong> Camión
                </div>
                <form method="POST" action="{{ route('trucks.store') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="card-block">
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">* Nombre</label>
                                <input type="text" class="form-control @if($errors->has('name')) is-invalid @endif" id="name" name="name" placeholder="Nombre del camión" value="{{ old('name') }}">
                                @if($errors->has('name'))
                                    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                              <label for="description">* Descripción</label>
                              <textarea class="form-control @if($errors->has('description')) is-invalid @endif" id="description" rows="3" name="description" placeholder="Descripción del camión">{{ old('description') }}</textarea>
                              @if($errors->has('description'))
                                  <div class="invalid-feedback">{{ $errors->first('description') }}</div>
                              @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="load_amount">* Capacidad de carga</label>
                                <input type="text" class="form-control @if($errors->has('load_amount')) is-invalid @endif" id="load_amount" name="load_amount" placeholder="ej: 25,000 kg" value="{{ old('load_amount') }}">
                                @if($errors->has('load_amount'))
                                    <div class="invalid-feedback">{{ $errors->first('load_amount') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="title">* Precio</label>
                                <input type="text" class="form-control @if($errors->has('price')) is-invalid @endif" id="price" name="price" placeholder="ej: 60,000" value="{{ old('price') }}">
                                @if($errors->has('price'))
                                    <div class="invalid-feedback">{{ $errors->first('price') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="featured_image">* Imágen principal</label>
                                <input-file-preview name="featured_image" accepted="image/*">
                                </input-file-preview>
                                @if($errors->has('featured_image'))
                                    <div class="invalid-feedback">{{ $errors->first('featured_image') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="specs">Características técnicas</label>
                                <textarea class="description form-control @if($errors->has('specs')) is-invalid @endif" rows="3" name="specs" placeholder="Características técnicas">{!! old('specs') !!}</textarea>
                                @if($errors->has('specs'))
                                    <div class="invalid-feedback">{{ $errors->first('specs') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="specs_image">Imágen para Características técnicas</label>
                                <input-file-preview name="specs_image" accepted="image/*">
                                </input-file-preview>
                                @if($errors->has('specs_image'))
                                    <div class="invalid-feedback">{{ $errors->first('specs_image') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="dimensions">Capacidades y Dimensiones</label>
                                <textarea class="description form-control @if($errors->has('dimensions')) is-invalid @endif" rows="3" name="dimensions" placeholder="Capacidad y dimensiones">{!! old('dimensiones') !!}</textarea>
                                @if($errors->has('dimensions'))
                                    <div class="invalid-feedback">{{ $errors->first('dimensions') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="dimensions_image">Imágen para Capacidades y Dimensiones</label>
                                <input-file-preview name="dimensions_image" accepted="image/*">
                                </input-file-preview>
                                @if($errors->has('dimensions_image'))
                                    <div class="invalid-feedback">{{ $errors->first('dimensions_image') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="accessories">Cabina y accesorios</label>
                                <textarea class="description form-control @if($errors->has('accessories')) is-invalid @endif" rows="3" name="accessories" placeholder="Cabina y accesorios">{!! old('accessories') !!}</textarea>
                                @if($errors->has('accessories'))
                                    <div class="invalid-feedback">{{ $errors->first('accessories') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="accessories_image">Imágen para Cabina y accesorios</label>
                                <input-file-preview name="accessories_image" accepted="image/*">
                                </input-file-preview>
                                @if($errors->has('accessories_image'))
                                    <div class="invalid-feedback">{{ $errors->first('accessories_image') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="catalog">Catálogo</label>
                                <input type="file" class="form-control-file form-control @if($errors->has('catalog')) is-invalid @endif" id="catalog" name="catalog" accept="application/pdf">
                                <small class="form-text text-muted">Catálogo en formato PDF.</small>
                                @if($errors->has('catalog'))
                                    <div class="invalid-feedback">{{ $errors->first('catalog') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="truck_family_id">* Familia</label>
                                <select class="form-control @if($errors->has('truck_family_id')) is-invalid @endif" id="truck_family_id" name="truck_family_id">
                                    @foreach($families as $family)
                                        <option value="{{ $family->id }}">{{ $family->name }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('truck_family_id'))
                                    <div class="invalid-feedback">{{ $errors->first('truck_family_id') }}</div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a href="{{ route('trucks.index') }}" class="btn btn-default">Volver</a>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/truck/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Editar Camión')

@section('breadcrumb')
    {!! Breadcrumbs::render('edit-truck', $truck) !!}
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card btn-shadow">
                <div class="card-header">
                    <strong>Editar</strong> Camión
                </div>
                <form method="POST" action="{{ route('trucks.update', $truck) }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                    <div class="card-block">
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">* Nombre</label>
                                <input type="text" class="form-control @if($errors->has('name')) is-invalid @endif" id="name" name="name" placeholder="Nombre del camión" value="{{ $truck->name }}">
                                @if($errors->has('name'))
                                    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                              <label for="description">* Descripción</label>
                              <textarea class="form-control @if($errors->has('description')) is-invalid @endif" id="description" rows="3" name="description" placeholder="Descripción del camión">{{ $truck->description }}</textarea>
                              @if($errors->has('description'))
                                  <div class="invalid-feedback">{{ $errors->first('description') }}</div>
                              @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="load_amount">* Capacidad de carga</label>
                                <input type="text" class="form-control @if($errors->has('load_amount')) is-invalid @endif" id="load_amount" name="load_amount" placeholder="ej: 25,000 kg" value="{{ $truck->load_amount }}">
                                @if($errors->has('load_amount'))
                                    <div class="invalid-feedback">{{ $errors->first('load_amount') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="title">* Precio</label>
                                <input type="text" class="form-control @if($errors->has('price')) is-invalid @endif" id="price" name="price" placeholder="ej: 60,000" value="{{ $truck->price }}">
                                @if($errors->has('price'))
                                    <div class="invalid-feedback">{{ $errors->first('price') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="featured_image">* Imágen principal</label>
                                <input-file-preview name="featured_image" accepted="image/*" @if($truck->featured_image) image="{{ $truck->featured_image }}" @endif>
                                </input-file-preview>
                                @if($errors->has('featured_image'))
                                    <div class="invalid-feedback">{{ $errors->first('featured_image') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="subtitle">Estado</label>
                                <div>
                                    <label class="switch switch-text switch-pill switch-primary">
                                        <input type="checkbox" name="status" class="switch-input" @if($truck->status) checked @endif>
                                        <span class="switch-label" data-on="On" data-off="Off"></span>
                                        <span class="switch-handle"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="specs"><h5>
                                    Características técnicas
                                </h5></label>
                                <textarea class="description form-control @if($errors->has('specs')) is-invalid @endif" rows="3" name="specs" placeholder="Características técnicas">{{ $truck->specs }}</textarea>
                                @if($errors->has('specs'))
                                    <div class="invalid-feedback">{{ $errors->first('specs') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="specs_image">Imágen para Características técnicas</label>
                                <input-file-preview name="specs_image" accepted="image/*" @if($truck->specs_image) image="{{ $truck->specs_image }}" @endif>
                                </input-file-preview>
                                @if($errors->has('specs_image'))
                                    <div class="invalid-feedback">{{ $errors->first('specs_image') }}</div>
                                @endif
                                <hr>
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="dimensions"><h5>
                                    Capacidades y Dimensiones
                                </h5></label>
                                <textarea class="description form-control @if($errors->has('dimensions')) is-invalid @endif" rows="3" name="dimensions" placeholder="Capacidad y dimensiones">{{ $truck->dimensions }}</textarea>
                                @if($errors->has('dimensions'))
                                    <div class="invalid-feedback">{{ $errors->first('dimensions') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="dimensions_image">Imágen para Capacidades y Dimensiones</label>
                                <input-file-preview name="dimensions_image" accepted="image/*" @if($truck->dimensions_image) image="{{ $truck->dimensions_image }}" @endif>
                                </input-file-preview>
                                @if($errors->has('dimensions_image'))
                                    <div class="invalid-feedback">{{ $errors->first('dimensions_image') }}</div>
                                @endif
                                <hr>
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="accessories"><h5>
                                    Cabina y accesorios
                                </h5></label>
                                <textarea class="description form-control @if($errors->has('accessories')) is-invalid @endif" rows="3" name="accessories" placeholder="Cabina y accesorios">{{ $truck->accessories }}</textarea>
                                @if($errors->has('accessories'))
                                    <div class="invalid-feedback">{{ $errors->first('accessories') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="accessories_image">Imágen para Cabina y accesorios</label>
                                <input-file-preview name="accessories_image" accepted="image/*" @if($truck->accessories_image) image="{{ $truck->accessories_image }}" @endif>
                                </input-file-preview>
                                @if($errors->has('accessories_image'))
                                    <div class="invalid-feedback">{{ $errors->first('accessories_image') }}</div>
                                @endif
                                <hr>
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="catalog">Catálogo</label>
                                @if($truck->catalog)
                                  <a href="{{ $truck->catalog }}">Ver PDF</a>
                                @endif
                                <input type="file" class="form-control-file form-control @if($errors->has('catalog')) is-invalid @endif" id="catalog" name="catalog" accept="application/pdf">
                                <small class="form-text text-muted">Catálogo en formato PDF.</small>
                                @if($errors->has('catalog'))
                                    <div class="invalid-feedback">{{ $errors->first('catalog') }}</div>
                                @endif
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="truck_family_id">* Familia</label>
                                <select class="form-control @if($errors->has('truck_family_id')) is-invalid @endif" id="truck_family_id" name="truck_family_id">
                                    @foreach($families as $family)
                                        <option value="{{ $family->id }}" @if($truck->truck_family_id == $family->id) selected @endif>{{ $family->name }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('truck_family_id'))
                                    <div class="invalid-feedback">{{ $errors->first('truck_family_id') }}</div>
                                @endif
                            </div>
                            <div class="col-sm-12 form-group">
                                <label for="description">Galería</label>
                                <drag-n-drop :images="{{ $truck->resources }}" name="{{ $truck->model_name }}" id="{{ $truck->id }}" url="{{ route('resources.store', $truck) }}"></drag-n-drop>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a href="{{ route('trucks.index') }}" class="btn btn-default">Volver</a>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/truck/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Camiones')

@section('breadcrumb')
    {!! Breadcrumbs::render('trucks') !!}
@endsection

@section('content')
    <div class="row justify-content-sm-between">
        <h3 class="m-0 font-weight-normal">Camiones</h3>
        <a href="{{ route('trucks.create') }}" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Nuevo</a>
    </div>
    <br>
    <div class="row">
        <table class="table col btn-shadow">
            <thead>
                <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Familia</th>
                <th>Estado</th>
                <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach($trucks as $truck)
                    <tr>
                        <td>{{ $truck->name }}</td>
                        <td>{{ $truck->price }}</td>
                        <td>{{ $truck->family->name }}</td>
                        <td>
                            @if($truck->status)
                                <span class="badge badge-success">Activo</span>
                            @else
                                <span class="badge badge-danger">Inactivo</span>
                            @endif
                        </td>
                        <td>
                            <a href="{{ route('trucks.edit', $truck) }}" class="btn btn-primary btn-sm">Editar</a>
                            <delete route="{{ route('trucks.destroy', $truck) }}" token="{{ csrf_token() }}"></delete>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    {{ $trucks->links() }}
    <div class="mt-3"></div>
@endsection