routes/admin.php
<?php

Auth::routes();

Route::get('{page}', 'FrontEndController@page');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:Administrador']], function () {
    Route::resource('users', 'UsersController');
    Route::resource('pages', 'PagesController');
    Route::resource('trucks', 'TrucksController');
    Route::resource('components', 'ComponentsController');
    Route::get('components/{type}/{id}/create', 'ComponentsController@create')->name('components.create');

    /* Parts */
    Route::get('parts/images', 'PartsController@filemanager')->name('parts.filemanager');
    Route::get('imagenes/conex', 'PartsController@getConnection')->name('imagenes.conex');
    Route::post('imagenes/conex', 'PartsController@postConnection')->name('imagenes.conex');

    Route::resource('resources', 'ResourcesController', [
      'only' => ['store', 'destroy']
  ]);
});

routes/web.php
<?php

Route::get('/', 'FrontEndController@home');

Route::redirect('/admin', '/admin/users');

Route::get('/camiones/{truck}', 'FrontEndController@truck')->name('truck');
Route::get('/repuestos/resultados', 'FrontEndController@search')->name('search');
Route::get('/repuestos/promocion', 'FrontEndController@onsale')->name('onsale');
Route::get('/repuestos/{part}', 'FrontEndController@part')->name('part');
Route::get('/carrito', 'CartController@cart')->name('cart');
Route::post('/parttocart', 'CartController@addPartToCart')->name('addPartToCart');
Route::post('/cart/update', 'CartController@update')->name('cart.update');
Route::get('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart/order', 'CartController@order')->name('cart.order')->middleware('auth');

Route::get('/success', 'CartController@success')->name('cart.success')->middleware('auth');

/* Routes related with admin */
include('admin.php');

app/User.php
<?php

namespace App;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'legal_id', 'address', 'city'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $users = User::paginate(15);
        return view('admin.user.index', compact('users'));
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        $roles = Role::all();
        return view('admin.user.create', \compact('roles'));
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6',
            'role' => 'required'
        ]);
        $data = $request->only(['name', 'email']);
        $data['password'] = \bcrypt($request->password);
        $user = User::create($data);
        $user->assignRole($request->role);
        return redirect()->route('users.index');
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit(User $user)
    {
        $roles = Role::all();
        return view('admin.user.edit', \compact('user', 'roles'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => [
                'required', 
                'string', 
                'email',
                'max:255',
                \Illuminate\Validation\Rule::unique('users')->ignore($user->id),
            ],
            'password' => 'sometimes|nullable|string|min:6',
            'role' => 'required'
        ]);
        $data =  $request->all();
        if($request->has('password')) {
            $data['password'] = bcrypt($request->password);
        }
        $data['status'] = $request->has('status') ? 1 : 0;
        $user->update($data);
        $user->syncRoles($request->role);
        return redirect()->route('users.index');
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index');
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Crear Usuario')

@section('breadcrumb')
    {!! Breadcrumbs::render('create-user') !!}
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card btn-shadow">
                <div class="card-header">
                    <strong>Crear</strong> Usuario
                </div>
                <form method="POST" action="{{ route('users.store') }}">
                    {{ csrf_field() }}
                    <div class="card-block">
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">Nombre</label>
                                <input type="text" class="form-control @if($errors->has('name')) is-invalid @endif" id="name" name="name" placeholder="Nombre de usuario">
                                @if($errors->has('name'))
                                    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">Email</label>
                                <input type="email" class="form-control @if($errors->has('email')) is-invalid @endif" id="email" name="email" placeholder="ejemplo@email.com">
                                @if($errors->has('email'))
                                    <div class="invalid-feedback">{{ $errors->first('email') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">Contraseña</label>
                                <input type="password" class="form-control @if($errors->has('password')) is-invalid @endif" id="password" name="password" placeholder="Mínimo 6 caracteres">
                                @if($errors->has('password'))
                                    <div class="invalid-feedback">{{ $errors->first('password') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                             <div class="form-group col-sm-12">
                                <label for="roles">Roles</label>
                                <select class="form-control @if($errors->has('role')) is-invalid @endif" id="roles" name="role">
                                    <option selected disabled>Seleccionar un rol</option>
                                    @foreach($roles as $role)
                                        <option value="{{ $role->name }}">{{ $role->name }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('role'))
                                    <div class="invalid-feedback">{{ $errors->first('role') }}</div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a href="{{ route('users.index') }}" class="btn btn-default">Volver</a>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Editar Usuario')

@section('breadcrumb')
    {!! Breadcrumbs::render('edit-user', $user) !!}
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card btn-shadow">
                <div class="card-header">
                    <strong>Editar</strong> Usuario
                </div>
                <form method="POST" action="{{ route('users.update', $user) }}">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="card-block">
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">Nombre</label>
                                <input type="text" class="form-control @if($errors->has('name')) is-invalid @endif" id="name" name="name" placeholder="Nombre de usuario" value="{{ $user->name }}">
                                @if($errors->has('name'))
                                    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">Email</label>
                                <input type="email" class="form-control @if($errors->has('email')) is-invalid @endif" id="email" name="email" placeholder="ejemplo@email.com" value="{{ $user->email }}">
                                @if($errors->has('email'))
                                    <div class="invalid-feedback">{{ $errors->first('email') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="title">Nueva Contraseña</label>
                                <input type="password" class="form-control @if($errors->has('password')) is-invalid @endif" id="password" name="password" placeholder="Mínimo 6 caracteres">
                                @if($errors->has('password'))
                                    <div class="invalid-feedback">{{ $errors->first('password') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                             <div class="form-group col-sm-12">
                                <label for="roles">Roles</label>
                                <select class="form-control @if($errors->has('role')) is-invalid @endif" id="roles" name="role[]">
                                    <option selected disabled>Seleccionar un rol</option>
                                    @foreach($roles as $role)
                                        <option value="{{ $role->name }}" @if($user->hasRole($role->name)) selected @endif>{{ $role->name }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('role'))
                                    <div class="invalid-feedback">{{ $errors->first('role') }}</div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a href="{{ route('users.index') }}" class="btn btn-default">Volver</a>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Usuarios')

@section('breadcrumb')
    {!! Breadcrumbs::render('users') !!}
@endsection

@section('content')
    <div class="row justify-content-sm-between">
        <h3 class="m-0 font-weight-normal">Usuarios</h3>
        <a href="{{ route('users.create') }}" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Nuevo</a>
    </div>
    <br>
    {{--  <div class="row">
        <div class="input-group btn-shadow">
            <input type="text" class="form-control btn-no-border" placeholder="Buscar usuarios..">
            <span class="input-group-btn">
                <button class="btn btn-primary btn-no-shadow" type="button"><i class="fa fa-search"></i> Buscar</button>
            </span>
        </div>
    </div>
    <br>  --}}
    <div class="row">
        <table class="table col btn-shadow">
            <thead>
                <tr>
                <th>#</th>
                <th>Nombres</th>
                <th>Correo</th>
                <th>Rol</th>
                <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                    <tr>
                        <th scope="row">{{ $user->id }}</th>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->getRoleNames()->first() }}</td>
                        <td>
                            <a href="{{ route('users.edit', $user) }}" class="btn btn-primary btn-sm">Editar</a>
                            @if($users->total() > 1)
                                <delete route="{{ route('users.destroy', $user) }}" token="{{ csrf_token() }}"></delete>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    {{ $users->links() }}

@endsection